/**
 * Harvests every {{TODO_CONFIRM}} token in the project into one list, so the
 * school can answer them in a single pass and nothing stays hidden in code.
 *   node tools/todo.js         write TODO_CONFIRM.md
 *   node tools/todo.js --list  print them
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')
const SCAN = ['src', 'tools']
const RX = /\{\{TODO_CONFIRM:\s*([\s\S]*?)\}\}/g

const GROUPS = [
  { title: 'Contact details', match: /phone|whatsapp|number|email|hours|holiday/i },
  { title: 'Address and location', match: /postal|street|address|geo|latitude|campus|branch/i },
  { title: 'Fees and stationery', match: /fee|rate|stationery|close time|date these/i },
  { title: 'People', match: /bio|principal|natalie|aldonia|memory|lorraine/i },
  { title: 'Classes and programmes', match: /ladybug|weekly programme|routine|menu|class/i },
  { title: 'Documents and downloads', match: /pdf|download|form|indemnity|planner/i },
  { title: 'Photography and consent', match: /consent|image-consent|photograph/i },
  { title: 'Legal and compliance', match: /popia|information officer|retention|registration|terms|operator/i },
  { title: 'Analytics and tagging', match: /gtm|turnstile|analytics|conversion|aco/i },
  { title: 'Redirects', match: /news|parent tips|consolidation/i }
]

async function walk (dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) out.push(...await walk(full))
    else if (/\.(js|json|md|css|html)$/.test(entry.name)) out.push(full)
  }
  return out
}

const found = new Map()
for (const base of SCAN) {
  for (const file of await walk(path.join(ROOT, base))) {
    const text = await readFile(file, 'utf8')
    const lines = text.split('\n')
    for (const [i, line] of lines.entries()) {
      for (const m of line.matchAll(RX)) {
        const body = m[1].replace(/\s+/g, ' ').trim()
        if (!found.has(body)) found.set(body, [])
        found.get(body).push(`${path.relative(ROOT, file)}:${i + 1}`)
      }
    }
  }
}

const items = [...found.entries()].map(([question, at]) => ({ question, at }))
const assigned = new Set()
const sections = GROUPS.map(g => ({
  title: g.title,
  items: items.filter(i => !assigned.has(i.question) && g.match.test(i.question) && (assigned.add(i.question), true))
})).filter(s => s.items.length)
const rest = items.filter(i => !assigned.has(i.question))
if (rest.length) sections.push({ title: 'Everything else', items: rest })

const md = `# TODO_CONFIRM

Every open question on the site, in one list, so it can be answered in a single
pass. Each one is rendered visibly on the page it affects — nothing is hidden in
code, and nothing has been guessed to make a page look finished.

**${items.length} open questions.**

Generated by \`node tools/todo.js\`. Do not edit by hand; answer the questions and
the tokens disappear from the build.

${sections.map(s => `## ${s.title}

${s.items.map(i => `- [ ] **${i.question}**\n  <br><sub>${i.at.join(' · ')}</sub>`).join('\n')}`).join('\n\n')}

---

## Why these are not simply filled in

This is a childcare site. A fabricated phone number, an unverified address in a
\`LocalBusiness\` schema, an invented staff qualification or a guessed closing
time are not cosmetic problems — they are the kind of error a parent acts on. The
brief's rule was that anything not traceable to the source content is emitted as
a question rather than an answer, and that is what these are.
`
if (process.argv.includes('--list')) console.log(md)
else { await writeFile(path.join(ROOT, 'TODO_CONFIRM.md'), md); console.log(`TODO_CONFIRM.md: ${items.length} open questions`) }
